# Generated by Django 5.0.4 on 2024-04-21 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_alter_schedule_end_time_alter_schedule_excuse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='day',
        ),
        migrations.AddField(
            model_name='places',
            name='schedule_fr',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='places_fr', to='chatbot.schedule'),
        ),
        migrations.AddField(
            model_name='places',
            name='schedule_mo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='places_mo', to='chatbot.schedule'),
        ),
        migrations.AddField(
            model_name='places',
            name='schedule_sa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='places_sa', to='chatbot.schedule'),
        ),
        migrations.AddField(
            model_name='places',
            name='schedule_su',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='places_su', to='chatbot.schedule'),
        ),
        migrations.AddField(
            model_name='places',
            name='schedule_th',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='places_th', to='chatbot.schedule'),
        ),
        migrations.AddField(
            model_name='places',
            name='schedule_tu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='places_tu', to='chatbot.schedule'),
        ),
        migrations.AddField(
            model_name='places',
            name='schedule_we',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='places_we', to='chatbot.schedule'),
        ),
    ]
